<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3912.50" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BusinessLayer">
      <HintPath>..\BusinessLayer\bin\Debug\net10.0\BusinessLayer.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>