<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="DataAccessLayer">
      <HintPath>..\DataAccessLayer\bin\Debug\net10.0\DataAccessLayer.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
